@API_HostAddress = http://localhost:5291

### Listar Imcs
GET http://localhost:5291/api/imc/listar

### Listar Imcs Por usuario
GET http://localhost:5291/api/imc/listarPorUsuario/1

### Cadastrar Usuarios
POST http://localhost:5291/api/Usuario/cadastrar
Content-Type: application/json

{
  "nome": "Henrique",
  "altura": 1.70,
  "peso": 65
}

### Criar IMC
POST http://localhost:5291/api/imc/cadastrar
Content-Type: application/json

{
  "UsuarioId": 3,
  "valor": 20.32
}

### Atualizar IMC
PUT http://localhost:5291/api/imc/atualizar/1
Content-Type: application/json

{
  "valor": 19.32
}